### PR TITLE
Andrea revision

### PR DESCRIPTION
**Pull request by AndreaSottana**
General refactoring and streamlining

### CODE REVIEW

**Review by elricwan — APPROVED** [review]

**Review by elricwan — APPROVED** [review]

**Review by elricwan — APPROVED** [review]

**Review by elricwan — APPROVED** [review]

**Comment by AndreaSottana** [comment]
Hello @elricwan 

If you approve the request, could you please merge it onto the master branch. It looks like it has been closed without merging.
Thanks

**Comment by elricwan** [comment]
I thought about that, the structure of the code now is consistent with the code in google colab, so we can keep it that way

**Comment by AndreaSottana** [comment]
Ok let's discuss tomorrow. My changes are mostly to make the README more fluent (and fixing some typos) as well as standardising the python code so it is more readable according to the PEP8 standard, as well as fixing some English typos. I do not change the actual underlying code. If you believe the changes I propose should not go to master, then let's have a meeting to discuss.
Thanks

**Comment by elricwan** [comment]
Sure

**Comment by AndreaSottana** [comment]
Closing this PR as changes have been merged from #4 instead

**Pull request closed without merging**
